version: '3.9'

services:
  summarization_youtube:
    container_name: summarization_youtube
    build: ./src 
    # since this is an endlessly running command the containers stays running
    command: [sh, -c, "cd /usr/src/ && ls -la && uvicorn app.summarize_youtube:app --reload --host 0.0.0.0 --port 8000"]
    restart: unless-stopped
    volumes:
      - ./src/:/usr/src/
    ports:
      - "${SERVICE_PORT}:8000"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command: ngrok http 8000

